catalog:
  app:
    persistence:
      endpoint: "bedrock-catalog-mysql.cs9sk0m6c164.us-east-1.rds.amazonaws.com:3306
Releasing state lock. This may take a few moments..."
orders:
  app:
    persistence:
      endpoint: "bedrock-orders-pg.cs9sk0m6c164.us-east-1.rds.amazonaws.com:5432
Releasing state lock. This may take a few moments..."
carts:
  app:
    persistence:
      dynamodb:
        tableName: "Acquiring state lock. This may take a few moments...
bedrock-carts
Releasing state lock. This may take a few moments..."
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::193854996687:role/project-bedrock-cluster-carts"
