apiVersion: v1
kind: ConfigMap
metadata:
  name: orders
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: retail-store
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: retail-store
    app.kubernetes.io/managed-by: kustomize
data:
  RETAIL_ORDERS_MESSAGING_PROVIDER: rabbitmq
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: orders-rabbitmq:5672
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: postgres
  RETAIL_ORDERS_PERSISTENCE_NAME: orders
