apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: ui
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: retail-store
    app.kubernetes.io/managed-by: kustomize
data:
  RETAIL_UI_THEME: default
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog
  RETAIL_UI_ENDPOINTS_CARTS: http://carts
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders
  RETAIL_UI_SEARCH_ENABLED: "false"
