apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  labels:
    app.kubernetes.io/part-of: retail-store
    app.kubernetes.io/managed-by: kustomize
spec:
  podSelector: {}
  policyTypes:
    - Ingress
